version: "3.3"

services:
  muchmore-rtc:
    image: 720208444934.dkr.ecr.eu-west-3.amazonaws.com/muchmore-rtc:latest
    environment:
      - PORT=3000
      - PUBLIC_PATH=/app/public
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.muchmore-rtc.rule=Host(`rtc.muchmore.be`)"
        - "traefik.http.routers.muchmore-rtc.entrypoints=websecure"
        - "traefik.http.routers.muchmore-rtc.tls=true"
        - "traefik.http.routers.muchmore-rtc.tls.certresolver=letsencrypt"
        - "traefik.http.services.muchmore-rtc.loadbalancer.server.port=3000"
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    external: true